events {}

http {
    upstream my_wordpress {
        server wp-app-1:80;
        server wp-app-2:80;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://my_wordpress;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}